version: '2'
catalog:
  name: Kubernetes
  version: v1.8.0-rancher4-etcdv3
  description: Rancher Kubernetes service
  minimum_rancher_version: v1.6.11-rc1
  upgrade_from: 0.0.0
  questions:
  - variable: CONSTRAINT_TYPE
    label: Plane Isolation
    description: Isolate the data, orchestration and compute planes via host labels. Set to required when running in production.
    required: true
    default: none
    type: enum
    options:
    - none
    - required
  - variable: CLOUD_PROVIDER
    label: Cloud Provider
    description: The cloud provider on which Kubernetes is running
    required: true
    default: rancher
    type: enum
    options:
    - rancher
    - aws
  - variable: RBAC
    description: Enable Kubernetes role-based access control with integrated Rancher authentication.
    label: Kubernetes RBAC
    required: true
    default: false
    type: boolean
  - variable: REGISTRY
    description: The registry to pull addon images and the optional pod infra container image. This should be set to the private registry from which the images for addon-services (i.e. helm, heapster, dashboard, dns) and the pod infra container image should be pulled.
    label: Private Registry for Add-Ons and Pod Infra Container Image
    required: false
    default: ""
    type: string
  - variable: ENABLE_RANCHER_INGRESS_CONTROLLER
    description: Deploy the Rancher ingress controller which automatically provisions Rancher load balancers in response to Kubernetes ingress creation events.
    label: Enable Rancher Ingress Controller
    required: true
    default: true
    type: boolean
  - variable: ENABLE_ADDONS
    label: Enable Kubernetes Add-ons
    description: Setting this to `false` will disable Dashboard, Helm, SkyDNS, and other Kubernetes add-on services. This is meant for advanced users who want to deploy custom versions of these add-ons.
    required: true
    default: true
    type: boolean
  - variable: POD_INFRA_CONTAINER_IMAGE
    label: Pod Infra Container Image
    description: The image whose network/ipc namespaces containers in each pod will use. It uses kubelet default if left empty. Do not add the private registry to this field, update the `Private Registry for Add-Ons and Pod Infra Container Image` field with the registry information.
    required: false
    default: "gcr.io/google_containers/pause-amd64:3.0"
    type: string
  - variable: BASE_IMAGE_NAMESPACE
    description: images namespace for Add-Ons and Pod Infra Container Image ( Default：google_containers ).
    label: Image namespace for  Add-Ons and Pod Infra Container Image
    required: false
    default: ""
    type: string
  - variable: HELM_IMAGE_NAMESPACE
    description: images namespace for kubernetes-helm ( Default：kubernetes-helm ).
    label: Image namespace for kubernetes-helm Image
    required: false
    default: ""
    type: string
  - variable: DNS_REPLICAS
    description: Number of replicas for SKY DNS service. Each replica would run on the separate host, so change the value according to your infrastructure.
    label: Sky DNS service scale
    required: false
    default: 1
    type: int
  - variable: SERVICE_CLUSTER_CIDR
    label: Service Cluster IP CIDR
    description: A CIDR notation IP range from which to assign service cluster IPs. This must not overlap with any IP ranges assigned to the cluster pod IP CIDR (10.42.0.0/16).
    required: true
    default: "10.43.0.0/16"
    type: string
  - variable: DNS_CLUSTER_IP
    label: KubeDNS cluster IP
    description: The IP address assigned to kubedns service. This must be within the range of Service Cluster IP CIDR.
    required: true
    default: "10.43.0.10"
    type: string
  - variable: KUBEAPI_CLUSTER_IP
    label: KubeAPI cluster IP for TLS certificate
    description: This is the IP address that will be added as a SAN to the TLS certificate for kubernetes api, this must matches the IP of the kubernetes master service which is the first IP of the Service Cluster IP CIDR.
    required: true
    default: "10.43.0.1"
    type: string
  - variable: AUDIT_LOGS
    description: Enable Audit logs to stdout for the kube-apiserver
    label: Audit Logs
    required: false
    default: false
    type: boolean
  - variable: INFLUXDB_HOST_PATH
    label: InfluxDB Host Path
    description: "Write Heapster metrics to an absolute path on the host. This may be network-attached storage."
    required: false
    type: string
  - variable: ADDITIONAL_KUBELET_FLAGS
    label: Additional Kubelet Flags
    required: false
    type: string
  - variable: ETCD_HEARTBEAT_INTERVAL
    label: Etcd Heartbeat Interval
    description: Time (in milliseconds) of a heartbeat interval.
    required: true
    default: 500
    type: int
  - variable: ETCD_ELECTION_TIMEOUT
    label: Etcd Election Timeout
    description: Time (in milliseconds) for an election to timeout.
    required: true
    default: 5000
    type: int
  - variable: RESTORE_BACKUP
    label: Restore Backup
    description: Automatically restore cluster state when Kubernetes stack is redeployed.
    required: true
    default: true
    type: boolean
  - variable: ENABLE_BACKUPS
    label: Enable Backups
    description: Periodically backup state to local volumes on all hosts where etcd is schedulable.
    required: true
    default: true
    type: boolean
  - variable: BACKUP_CREATION
    label: Backup Creation Period
    description: Create a backup after this amount of time passes. Must conform to duration format
    required: true
    default: 15m0s
    type: string
  - variable: BACKUP_RETENTION
    label: Backup Retention Period
    description: Expire a backup after this amount of time passes. Must conform to duration format
    required: true
    default: 24h
    type: string
  - variable: RANCHER_LB_SEPARATOR
    description: Separator used in Rancher LB names generated by ingress controller
    label: Rancher LB name separator
    required: false
    default: rancherlb
    type: string
  - variable: HTTP_PROXY
    description: "To be used when Kubernetes services are deployed on host(s) behind a proxy, i.e.: http(s)://<fqdn>:<port>"
    label: HTTP proxy to be used by Kubernetes services
    required: false
    type: string
  - variable: NO_PROXY
    description: Comma separated string used to be excluded from the proxy
    label: no_proxy to be used by Kubernetes services
    required: false
    default: rancher.internal,cluster.local,rancher-metadata,rancher-kubernetes-auth,kubernetes,169.254.169.254,169.254.169.250,10.42.0.0/16,10.43.0.0/16
    type: string

services:
  kubernetes:
    metadata:
      sans:
      - "IP:${KUBEAPI_CLUSTER_IP}"
    health_check:
      port: 6443
      interval: 2000
      response_timeout: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      initializing_timeout: 60000
      reinitializing_timeout: 60000
    retain_ip: true

  etcd:
    retain_ip: true
    
  rancher-kubernetes-agent:
    health_check:
      request_line: GET /healthcheck HTTP/1.0
      port: 10240
      interval: 2000
      response_timeout: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      initializing_timeout: 60000
      reinitializing_timeout: 60000

  scheduler:
    health_check:
      request_line: GET /healthz HTTP/1.0
      port: 10251
      interval: 2000
      response_timeout: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      initializing_timeout: 60000
      reinitializing_timeout: 60000

  controller-manager:
    health_check:
      request_line: GET /healthz HTTP/1.0
      port: 10252
      interval: 2000
      response_timeout: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      initializing_timeout: 60000
      reinitializing_timeout: 60000

  kubectld:
    health_check:
      port: 10240
      interval: 2000
      response_timeout: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      initializing_timeout: 60000
      reinitializing_timeout: 60000
